DEVICE: cuda
RANDOM_SEED: 42

MODEL:
  NAME          : efficientnet_b4
  NUM_CLASSES   : 2
  PRETRAINED    : True

DATASET:
  TRAIN_DATA_DIR: [
    "data/C001",
    "data/C002",
    "data/C003",
    "data/Cataract_Detection-using-CNN",
    "data/Cataract-Detection-and-Classification",
    "data/kaggle_cataract_kersh",
    # "data/kaggle_cataract_nand"
  ]
  NUM_WORKERS   : 16
  N_FOLDS       : 5

TRAIN: 
  BATCH_SIZE    : 128    
  EPOCHS        : 100    
  PATIENCE      : 10     
  AMP           : True   

LOSS:
  NAME: CrossEntropyLoss

OPTIMIZER:
  NAME: AdamW
  lr: 0.001             
  weight_decay: 0.0001  

SCHEDULER:
  scheduler_name: 'ReduceLROnPlateau' 
  mode: 'max'
  factor: 0.1
  patience: 5
  min_lr: 0.000001

SAVE_DIR        : './outputs'

WANDB_PROJECT   : "cataract-detection"