DEVICE: cuda
RANDOM_SEED: 321

MODEL:
  NAME          : 'Swin_Large'
  NUM_CLASSES   : 2
  PRETRAINED    : True

DATASET:
  TRAIN_DATA_DIR: [
    "../dataset/data/C002",
    "../dataset/data/C003",
    "../dataset/data/Cataract_Detection-using-CNN",
    "../dataset/data/Cataract-Detection-and-Classification",
  ]
  NUM_WORKERS   : 16
  N_FOLDS       : 5

TRAIN:
  BATCH_SIZE    : 128
  EPOCHS        : 200
  PATIENCE      : 10
  AMP           : True

LOSS:
  NAME: CrossEntropyLoss

OPTIMIZER:
  NAME: Adam
  lr: 0.001
  weight_decay: 0.0001

SCHEDULER:
  scheduler_name: 'ReduceLROnPlateau'
  mode: 'max'
  factor: 0.1
  patience: 5
  min_lr: 0.000001

SAVE_DIR        : '../outputs'

WANDB_PROJECT   : "cataract-detection"