DEVICE: cuda
RANDOM_SEED: 321

MODEL:
  NAME          : 'FastViT'
  NUM_CLASSES   : 2
  PRETRAINED    : True

DATASET:
  TRAIN_DATA_DIR: [
    "../dataset/final/train"
  ]
  NUM_WORKERS   : 16
  RATIO         : 0.85

TRAIN:
  BATCH_SIZE    : 64
  EPOCHS        : 200
  PATIENCE      : 30
  AMP           : True

LOSS:
  NAME: CrossEntropyLoss

OPTIMIZER:
  NAME: AdamW
  lr: 0.0002
  weight_decay: 0.0001

SCHEDULER:
  scheduler_name: 'ReduceLROnPlateau'
  mode: 'max'
  factor: 0.1
  patience: 5
  min_lr: 0.000001

SAVE_DIR        : 'outputs'

WANDB_PROJECT   : "cataract-detection"